name: makula_oem
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.1+54

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg:
  get:
  readmore: ^2.2.0
  graphql_flutter: ^5.1.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0 #to format dates
  pubnub: ^4.2.1
  flutter_dotenv: ^5.0.2
  emoji_picker_flutter: ^1.3.1
  flutter_chat_bubble: ^2.0.0
  timelines: ^0.1.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  file_picker:
  url_launcher:
  pull_to_refresh: ^2.0.0
  flutter_flavor: ^3.1.1
  flutter_local_notifications: ^9.9.1
  rxdart: ^0.27.5
  provider: ^6.0.3
  freezed: ^2.1.0+1
  sealed_unions: ^3.0.3+1
  flutter_downloader: ^1.8.3+2
  external_path: ^1.0.3
  badges: ^2.0.3
  video_player: ^2.4.7
  permission_handler: ^10.0.0
  dropdown_search: ^3.0.1
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  sealed_generators:
  freezed_annotation: ^2.1.0
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/images/
