name: makula_oem
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+51

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  get:
  readmore: ^2.1.0
  graphql_flutter: ^5.0.1
  shared_preferences: ^2.0.13
  intl: ^0.17.0 #to format dates
  pubnub: ^4.1.0
  flutter_dotenv: ^5.0.2
  emoji_picker_flutter: ^1.1.2
  flutter_chat_bubble: ^2.0.0
  timelines: ^0.1.0
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  file_picker: ^4.5.1
  url_launcher: ^6.0.20
  pull_to_refresh: ^2.0.0
  flutter_flavor: ^3.0.3
  flutter_local_notifications: ^9.4.0
  rxdart: ^0.27.3
  provider: ^6.0.2
  freezed: ^1.1.1
  sealed_unions: ^3.0.3+1
  flutter_downloader: ^1.7.3
  external_path: ^1.0.1
  badges: ^2.0.3
  video_player: ^2.4.5
  permission_handler: ^10.0.0
  dropdown_search: ^3.0.1
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  sealed_generators:
  freezed_annotation: ^1.1.0
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/images/
