name: makula_oem
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.2.4+62

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg:
  get:
  readmore: ^2.2.0
  graphql_flutter: ^5.1.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1 #to format dates
  pubnub: ^4.3.1
  flutter_dotenv: ^5.1.0
  emoji_picker_flutter: ^1.6.3
  flutter_chat_bubble: ^2.0.2
  timelines: ^0.1.0
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  file_picker:
  url_launcher:
  pull_to_refresh: ^2.0.0
  flutter_flavor: ^3.1.3
  flutter_local_notifications: ^16.2.0
  rxdart: ^0.27.7
  provider: ^6.1.1
  freezed: ^2.4.6
  sealed_unions: ^3.0.3+1
  flutter_downloader: ^1.11.5
  external_path: ^1.0.3
  badges: ^3.1.2
  video_player: ^2.8.1
  permission_handler: ^11.1.0
  dropdown_search: ^5.0.6
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1
  webview_flutter: ^3.0.4 #DONT UPDATE THIS

  connectivity_plus: ^5.0.2
  floor: ^1.4.2
  sqflite: ^2.3.0
  flutter_html: ^3.0.0-alpha.1 #DONT UPDATE THIS
  signature: ^5.4.1
  path: ^1.8.3
  path_provider: ^2.1.1
  http: ^1.1.2
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed_annotation: ^2.4.1
  floor_generator: ^1.4.2
#  hive_generator: ^2.0.1
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - lib/views/screens/dashboard/tabbar/tickets/provider/
