// ignore_for_file: constant_identifier_names

class OfflineResources {
  OfflineResources._();

  //BOX
  static const String LOGIN_TOKEN_BOX = 'LOGIN_TOKEN_BOX';
  static const String CURRENT_USER_BOX = 'CURRENT_USER_BOX';
  static const String OEM_STATUS_BOX = 'OEM_STATUS_BOX';
  static const String LIST_USER_OPEN_TICKETS_BOX = 'LIST_USER_OPEN_TICKETS_BOX';
  static const String LIST_USER_CLOSE_TICKETS_BOX = 'LIST_USER_CLOSE_TICKETS_BOX';
  static const String LIST_OPEN_TICKETS_BOX = 'LIST_OPEN_TICKETS_BOX';
  static const String LIST_CLOSE_TICKETS_BOX = 'LIST_CLOSE_TICKETS_BOX';
  static const String GET_TICKET_DETAIL_RESPONSE_BOX = 'GET_TICKET_DETAIL_RESPONSE_BOX';
  static const String LIST_ASSIGNEE_BOX = 'LIST_ASSIGNEE_BOX';


  //KEYS

  static const String LOGIN_TOKEN_RESPONSE = 'LOGIN_TOKEN_RESPONSE';
  static const String CURRENT_USER_RESPONSE = 'CURRENT_USER_RESPONSE';
  static const String OEM_STATUS_RESPONSE = 'OEM_STATUS_RESPONSE';
  static const String LIST_USER_OPEN_TICKETS_RESPONSE = 'LIST_USER_OPEN_TICKETS_RESPONSE';
  static const String LIST_USER_CLOSE_TICKETS_RESPONSE = 'LIST_USER_CLOSE_TICKETS_RESPONSE';
  static const String LIST_OPEN_TICKET_RESPONSE = 'LIST_OPEN_TICKET_RESPONSE';
  static const String LIST_CLOSE_TICKET_RESPONSE = 'LIST_CLOSE_TICKET_RESPONSE';
  static const String GET_TICKET_DETAIL_RESPONSE = 'GET_TICKET_DETAIL_RESPONSE';
  static const String LIST_ASSIGNEE_RESPONSE = 'LIST_ASSIGNEE_RESPONSE';
}
